<?php 
    get_template_part('template-parts/home-page/section-banner/index'); 
    get_template_part('template-parts/home-page/section-highlights/index'); 
    get_template_part('template-parts/home-page/section-destinations/index');
    get_template_part('template-parts/home-page/section-inspiring/index');
    get_template_part('template-parts/home-page/section-holidaystypes/index');
    get_template_part('template-parts/components/section-reason/index');
    get_template_part('template-parts/home-page/section-reviews/index');
    get_template_part('template-parts/home-page/section-travelguide/index');
?>
